name: Deploy to Render

on:
  push:
    branches:
      - main  # ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Disparar deploy do backend
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

      - name: Disparar deploy do frontend
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
